package entity;
// Generated 20/01/2019 03:10:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private int id;
     private String name;
     private String catchPhrase;
     private String bs;
     private Set users = new HashSet(0);

    public Company() {
    }

	
    public Company(int id, String catchPhrase, String bs) {
        this.id = id;
        this.catchPhrase = catchPhrase;
        this.bs = bs;
    }
    public Company(int id, String name, String catchPhrase, String bs, Set users) {
       this.id = id;
       this.name = name;
       this.catchPhrase = catchPhrase;
       this.bs = bs;
       this.users = users;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCatchPhrase() {
        return this.catchPhrase;
    }
    
    public void setCatchPhrase(String catchPhrase) {
        this.catchPhrase = catchPhrase;
    }
    public String getBs() {
        return this.bs;
    }
    
    public void setBs(String bs) {
        this.bs = bs;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


