package entity;
// Generated 20/01/2019 03:10:52 AM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private Company company;
     private String name;
     private String username;
     private String email;
     private String street;
     private String suite;
     private String city;
     private String zipcode;
     private double lat;
     private double lng;
     private String phone;
     private String website;

    public User() {
    }

    public User(int id, Company company, String name, String username, String email, String street, String suite, String city, String zipcode, double lat, double lng, String phone, String website) {
       this.id = id;
       this.company = company;
       this.name = name;
       this.username = username;
       this.email = email;
       this.street = street;
       this.suite = suite;
       this.city = city;
       this.zipcode = zipcode;
       this.lat = lat;
       this.lng = lng;
       this.phone = phone;
       this.website = website;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getSuite() {
        return this.suite;
    }
    
    public void setSuite(String suite) {
        this.suite = suite;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }
    public double getLat() {
        return this.lat;
    }
    
    public void setLat(double lat) {
        this.lat = lat;
    }
    public double getLng() {
        return this.lng;
    }
    
    public void setLng(double lng) {
        this.lng = lng;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }




}


