package com.prueba.calculadorasoap.entity;
// Generated 20/01/2019 04:58:23 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name="company"
    ,catalog="calculadorasoap"
)
public class Company  implements java.io.Serializable {


     private int id;
     private String name;
     private String catchPhrase;
     private String bs;
     private Set users = new HashSet(0);

    public Company() {
    }

	
    public Company(int id) {
        this.id = id;
    }
    public Company(int id, String name, String catchPhrase, String bs, Set users) {
       this.id = id;
       this.name = name;
       this.catchPhrase = catchPhrase;
       this.bs = bs;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="catchPhrase", length=100)
    public String getCatchPhrase() {
        return this.catchPhrase;
    }
    
    public void setCatchPhrase(String catchPhrase) {
        this.catchPhrase = catchPhrase;
    }

    
    @Column(name="bs", length=100)
    public String getBs() {
        return this.bs;
    }
    
    public void setBs(String bs) {
        this.bs = bs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="company")
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


