package com.prueba.calculadorasoap.entity;
// Generated 20/01/2019 04:58:23 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="calculadorasoap"
)
public class User  implements java.io.Serializable {


     private int id;
     private Company company;
     private String name;
     private String username;
     private String email;
     private String street;
     private String suite;
     private String city;
     private String zipcode;
     private double lat;
     private double lng;
     private String phone;
     private String website;

    public User() {
    }

    public User(int id, Company company, String name, String username, String email, String street, String suite, String city, String zipcode, double lat, double lng, String phone, String website) {
       this.id = id;
       this.company = company;
       this.name = name;
       this.username = username;
       this.email = email;
       this.street = street;
       this.suite = suite;
       this.city = city;
       this.zipcode = zipcode;
       this.lat = lat;
       this.lng = lng;
       this.phone = phone;
       this.website = website;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company", nullable=false)
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="username", nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="street", nullable=false, length=100)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="suite", nullable=false, length=100)
    public String getSuite() {
        return this.suite;
    }
    
    public void setSuite(String suite) {
        this.suite = suite;
    }

    
    @Column(name="city", nullable=false, length=100)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="zipcode", nullable=false, length=100)
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    
    @Column(name="lat", nullable=false, precision=22, scale=0)
    public double getLat() {
        return this.lat;
    }
    
    public void setLat(double lat) {
        this.lat = lat;
    }

    
    @Column(name="lng", nullable=false, precision=22, scale=0)
    public double getLng() {
        return this.lng;
    }
    
    public void setLng(double lng) {
        this.lng = lng;
    }

    
    @Column(name="phone", nullable=false, length=50)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="website", nullable=false, length=100)
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }




}


