package com.prueba.calculadorasoap.entity;
// Generated 20/01/2019 11:49:57 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="calculadorasoap"
)
public class User  implements java.io.Serializable {


     private int id;
     private String name;
     private String username;
     private String email;
     private String street;
     private String suite;
     private String city;
     private String zipcode;
     private double lat;
     private double lng;
     private String phone;
     private String website;
     private String companyName;
     private String catchPhrase;
     private String bs;

    public User() {
    }

    public User(int id, String name, String username, String email, String street, String suite, String city, String zipcode, double lat, double lng, String phone, String website, String companyName, String catchPhrase, String bs) {
       this.id = id;
       this.name = name;
       this.username = username;
       this.email = email;
       this.street = street;
       this.suite = suite;
       this.city = city;
       this.zipcode = zipcode;
       this.lat = lat;
       this.lng = lng;
       this.phone = phone;
       this.website = website;
       this.companyName = companyName;
       this.catchPhrase = catchPhrase;
       this.bs = bs;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="username", nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="street", nullable=false, length=100)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="suite", nullable=false, length=100)
    public String getSuite() {
        return this.suite;
    }
    
    public void setSuite(String suite) {
        this.suite = suite;
    }

    
    @Column(name="city", nullable=false, length=100)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="zipcode", nullable=false, length=100)
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    
    @Column(name="lat", nullable=false, precision=22, scale=0)
    public double getLat() {
        return this.lat;
    }
    
    public void setLat(double lat) {
        this.lat = lat;
    }

    
    @Column(name="lng", nullable=false, precision=22, scale=0)
    public double getLng() {
        return this.lng;
    }
    
    public void setLng(double lng) {
        this.lng = lng;
    }

    
    @Column(name="phone", nullable=false, length=50)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="website", nullable=false, length=100)
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }

    
    @Column(name="company_name", nullable=false, length=100)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    
    @Column(name="catchPhrase", nullable=false, length=100)
    public String getCatchPhrase() {
        return this.catchPhrase;
    }
    
    public void setCatchPhrase(String catchPhrase) {
        this.catchPhrase = catchPhrase;
    }

    
    @Column(name="bs", nullable=false, length=100)
    public String getBs() {
        return this.bs;
    }
    
    public void setBs(String bs) {
        this.bs = bs;
    }




}


